### ISSUE TITLE
UX improvements

### ISSUE THREAD

**Issue by Brombeis** [afrojezus/mirai#1]
## General
- [x] Some elements around the app are clickable but don't have `cursor: pointer` when hovered - it could be confusing for users. Some examples are the "collections" boxes in the homepage and the avatar circle when signing up.
- [x] Some areas are empty and thus only show the page's title, they might be improved by adding some "There's nothing here" and variants of it here and there (e.g. Popularity, Score, Collections)
- [x] The browser's default scrollbar [looks off compared to the rest of the site which is quite dark](https://user-images.githubusercontent.com/24258547/36951282-2c3ba49c-2002-11e8-9bf0-f61204a96f32.png); It could use some customization.
- [x] Clicking on the logo should bring to the homepage as well.

## Posts
- [x] It's currently possible to submit empty posts by clicking on "Post"
- [x] I cannot get to a user's profile by clicking on the name in the post
- [x] Sometimes, the "delete" feature bugs out. The bug can be reproduced by adding a few posts, then trying to delete them in quick succession - sometimes, some of them don't get removed.

## Signup
- [x] The button to switch between "Sign in" and "Sign up" does not immediately make its purpose obvious. It acts like a switch but almost looks like the button meant to actually submit the form. Could it be improved somehow? Also, the text ends up on two lines.
- [x] The circle shown when picking the avatar could be improved - why not stick a "picture" icon inside it? The same could be said for [the square shown in the Settings area when changing the background](https://user-images.githubusercontent.com/24258547/36951230-69a6aff8-2001-11e8-832a-e964c840dacb.png)

## Settings
- [x] The difference between Nickname and Username is not explained.
- [x] Spacing is [a bit off](https://user-images.githubusercontent.com/24258547/36951246-9da410c0-2001-11e8-9f6c-04c58728acb4.png)
- [x] I think the name of the setting and its switch are too far from each other on wide screens, maybe it could be improved by giving the settings' container a max-width and centering it or something along those lines, as long as it doesn't make the area look off compared to the rest of the site.
- [x] Changing the language and clicking on "Cancel" sets the <select> to an empty value instead of back to the previous language.

**Comment by afrojezus** [comment]
thanks, these issues have been addressed in the latest commit now.
